version: '2.5'

services:
  postgres-teste:
    build: ./postgres/Dockerfile_postgres
    restart: always
    env_file:
      - ./config/postgres.env
    ports:
      - "15432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - sefis-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./config/pgadmin.env
    ports:
      - "16543:80"
    depends_on:
      - postgres-teste
    networks:
      - sefis-network

networks:
  sefis-network:
    driver: bridge